wandb_version: 1

Images:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662324270.608247
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.2
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 1
cnn_layers:
  desc: null
  value: 5
epochs:
  desc: null
  value: 100
in_size_0:
  desc: null
  value: 14
in_size_1:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.005
n_attention_heads:
  desc: null
  value: 8
n_embedding_channels:
  desc: null
  value: 16
n_transformer_blocks:
  desc: null
  value: 5
